# Generated by Django 5.2.4 on 2025-07-10 04:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.IntegerField()),
                ("cycle", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="manual_logs/"),
                ),
                ("tag", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="cycle",
            field=models.IntegerField(
                choices=[
                    (0, "Germination"),
                    (1, "Seedling"),
                    (2, "Vegetative"),
                    (3, "Maturing"),
                    (4, "Harvest-ready"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name="sensorreading",
            name="cycle",
            field=models.IntegerField(
                choices=[
                    (0, "Germination"),
                    (1, "Seedling"),
                    (2, "Vegetative"),
                    (3, "Maturing"),
                    (4, "Harvest-ready"),
                ]
            ),
        ),
    ]
